### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by joseluu** [glmcdona/strings2#1]
Hello,

the project seem to be missing dirent.h, and string_hashes.h, I took direct.h from project https://github.com/tronkko/dirent/tree/master/include.

What about string_hashes.h ?  It works without it, no missing symbols.

Best

**Comment by glmcdona** [comment]
Thanks, I will update this tonight to include the string_hashes.h and refer to a different version of dirent.h. Dirent.h used to be a standard library in the older versions of the Visual C++ compiler.

**Comment by glmcdona** [comment]
Thanks joseluu. I've added the missing 'string_hashes.h' and added an open-source version of 'dirent.h'. I tested downloading the project as a 'zip', and opening it with Visual Studio 2015. After upgrading the project it compiles successfully with no configuration needed now :)
