### ISSUE TITLE
-b: Bytes of file to scan

### ISSUE THREAD

**Issue by emmanueltsukerman** [glmcdona/strings2#3]
Hello,

Does strings2 offer an option to scan only part of a file? Certain files can output a very large collection of strings and for practical reasons I would like to truncate the operation to save time and memory, e.g., by having an option of the form
-b: Bytes of file to scan.

**Comment by glmcdona** [comment]
Added in https://github.com/glmcdona/strings2/pull/7#issue-1252193977. Many years too late, my apologies!
