### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by lyubchev** [glmcdona/strings2#5]
Can you add a feature where when a user dumps the memory from a process, together with the strings outputed to a file add their addresses (offset), for example:
**{address}:{string}\n** instead of:
**{string}\n**

Thanks!

**Comment by glmcdona** [comment]
Added in https://github.com/glmcdona/strings2/pull/7#issue-1252193977. Dump a process with the `-s` flag to add the memory addresses that the string was found at. Also add `-f` flag to include the module name. Eg:

* ```strings2.exe -s -f -pid 0x232 > strings.txt```

With both these flags it'll dump strings as follows:

```
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde0e6,0x7ffbb1dde0f4),040904E4
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde0fe,0x7ffbb1dde112),CompanyName
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde118,0x7ffbb1dde13a),NVIDIA Corporation
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde146,0x7ffbb1dde162),FileDescription
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde168,0x7ffbb1dde1ae),NVIDIA D3D10 Driver, Version 392.59
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde1ba,0x7ffbb1dde1ce),FileVersion
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde1d4,0x7ffbb1dde1ec),23.21.13.9259
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde1f6,0x7ffbb1dde20c),InternalName
Notepad.exe:nvwgf2umx.dll@0x7ffbb1dde000,(0x7ffbb1dde210,0x7ffbb1dde21e),nvwgf2um
```

A few years too late, sorry! Giving the project a bit of a revamp now.
